default:
  image: ubuntu:latest

deploy-prod:
  only:
    - main
  stage: deploy
  before_script:
    - ls -la
    - pwd
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat $SSH_KEY_EC2
    - echo "$(cat $SSH_KEY_EC2)" >> ~/.ssh/ammaru.pem
    - chmod 400 ~/.ssh/ammaru.pem
    - cat ~/.ssh/ammaru.pem
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - apt-get update -y
    - apt-get -y install rsync
  script:
    - >- 
      ssh -i ~/.ssh/ammaru.pem ubuntu@$EC2_ADDRESS \
      'git config --global --replace-all user.name "Ammar Chalifah"
      && git config --global --replace-all user.email "ammar.chalifah@gmail.com"
      '
    - >-
      ssh -i ~/.ssh/ammaru.pem ubuntu@$EC2_ADDRESS \
      '
      if [ -d airflow-pipeline ]; 
      then cd airflow-pipeline
      && git status
      && git restore .env
      && git add .
      && git pull --rebase
      && git status
      && sed -i s:%AIRFLOW_UID%:'"$(id -u)"':g .env
      && sed -i s:%AIRFLOW_GID%:0:g .env
      && sed -i s:%_AIRFLOW_WWW_USER_USERNAME%:'"$_AIRFLOW_WWW_USER_USERNAME"':g .env
      && sed -i s:%_AIRFLOW_WWW_USER_PASSWORD%:'"$_AIRFLOW_WWW_USER_PASSWORD"':g .env; 
      else git clone https://'"$GITLAB_USERNAME"':'"$GITLAB_PASSWORD"'@gitlab.com/marukun/airflow-pipeline.git
      && cd airflow-pipeline 
      && ls -la 
      && chmod 777 logs
      && sed -i s:%AIRFLOW_UID%:'"$(id -u)"':g .env
      && sed -i s:%AIRFLOW_GID%:0:g .env
      && sed -i s:%_AIRFLOW_WWW_USER_USERNAME%:'"$_AIRFLOW_WWW_USER_USERNAME"':g .env
      && sed -i s:%_AIRFLOW_WWW_USER_PASSWORD%:'"$_AIRFLOW_WWW_USER_PASSWORD"':g .env
      && docker-compose up airflow-init; 
      fi'
    - >-
      ssh -i ~/.ssh/ammaru.pem ubuntu@$EC2_ADDRESS \
      'cd airflow-pipeline &&
      if [ docker ps | grep -q keyword ]; 
      then docker-compose down && docker-compose up -d --build; 
      else docker-compose up -d --build; 
      fi;'